### ISSUE TITLE
Content Work Plan

### ISSUE THREAD

**Issue by VB10** [VB10/Dart-Language-Full-Course#1]
- [x] what is dart lang
- [x] history
- [x] setup
- [x] ide
- [x] dartpad
- [x] basic start with print
- [x] How to declare variables
- [x] String , int, double type
- [x] Print 
- [x] Sample 1 : sum two numbers and assignto string value
- [x] Sample 2: show string side by side
- [x] var
- [x] final
- [x] const
- [x] static
- [x] Sample2: Calculate basket total value then mulitply with constant
- [x] if else else if
- [x] switch case
- [x] operator ++,-,
- [x] Sample3: Control user money if money bigger then 100, you could say 'rich' otherwise say it 'poor'
- [x] Sampe4: Bank credit calculation if user select first muliplty 1x etc.
- [x] List, Generic List, Lıst generate, ...,
- [x] Map, key value etc
- [x] Sample 5: Calculute 10 users money
- [x] Functıon
- [x] compute
- [x] paramater
- [x] void,return
- [x] optionel required default
- [x] sampl6 : write user dept calculator (total money and dept wıll be return resutl)
- [x] Class
- [x] Cosntuctor, factory consutroctor
- [x] singleton
- [x] Nullable veriable
- [x] normal varibale
- [x] Sample7: Create user class with money, name id and show name method
- [x] Method ovveride toString and ==
- [x] extension
- [x] mixin
- [x] abstact class
- [x] extend
- [x] enum, name
- [x] implement
- [x] Sample8 : Craetea admin user normal user and super user, super user have some other operatıons. create product user1
- [x] as is is! 
- [x] assigment operators
- [x] condintial expreison
- [x] casecade notion .. ?.. 
- [x] Sample 8.1: Control user is it valid?
- [x] List operation where
- [x] delete
- [x] single where
- [x] contains
- [x] any
- [x] map
- [ ] Map Entry
- [x] join
- [x] expend
- [x] addAll
- [x] Sample 9: where is my special cat id 11 
- [x] Sample 10: do you have red?
- [x] Sampl11: how can i fetch only my child from parents
- [x] Sample12: Remove od from list with 100 items
- [x] Encapsulatıon
- [x] Polymorphism
- [x] Solid
- [x] Single Responsibility Principle (SRP), Open closed Principle (OSP), Liskov substitution Principle (LSP), Interface Segregation Principle (ISP), and Dependency Inversion Principle (DIP
- [x] Sampe13: Wrıte first user manager with clean princibles
- [x] Future
- [x] Future.all , any etc.
- [x] Sync
- [x] Stream
- [x] event loop
- [ ] sample 14: Write first delayed function
- [ ] sample 15: First stream objet listener
- [x] try catch finally
- [ ] assert
- [x] exceptions
- [x] sample16: control to value right and is it has any problem
- [x] Generic
- [x] Restrict prramtertry class extends A
- [x] typdesf
- [x] metadete
- [ ] comments
- [x] Lexical closures nested functions

**Comment by volkankoc** [comment]
wonderful plan. I waiting for your lessons.

**Comment by VB10** [comment]
V1 ready

**Comment by VB10** [comment]
v2 ready

**Comment by VB10** [comment]
v3 ready

**Comment by VB10** [comment]
v5 ready
